spring.application.name=medapp
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/MedApp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forza il percorso di Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# Abilita l'interfaccia
springdoc.swagger-ui.enabled=true

